---
- hosts: gnome
  become: True
  remote_user: ansible
#  vars:
#    ansible_become_pass: Mk090911
  tasks:
    - name: Instalacja wymaganych pakietow do autoupdate
      apt:
        name:
        - unattended-upgrades
        cache_valid_time: 86400
  #####################
    - name: Przekopiowanie template
      copy:
        content: |
         APT::Periodic::Update-Package-Lists "1";
         APT::Periodic::Unattended-Upgrade "1";
        dest: /etc/apt/apt.conf.d/20auto-upgrades
    - name: Konfiguracja aktualizacji automatycznych
      template:
          src: templates/50unattended-upgrades
          dest: /etc/apt/apt.conf.d/50unattended-upgrades
    - name: Przekopiowanie zdefiniowanego pliku z banerem informacyjnym
      template:
          src: templates/greeter.dconf-defaults
          dest: /etc/gdm3/greeter.dconf-defaults
    - name: Ustawieenie wygaszacza
      ansible.builtin.shell: sudo -Hu mmk dbus-launch gsettings set org.gnome.desktop.session idle-delay 3600
    - name: ufw enabled
      community.general.ufw:
        state: "enabled"
        policy: "deny"
        logging: "on"
    - name: ufw rules
      community.general.ufw:
        rule: "allow"
        port: "{{ item }}"
        proto: "tcp"
      with_items:
        - "22"
        - "80"
        - "443"
    - name: Set timezone to Europe/Warsaw
      community.general.timezone:
        name: Europe/Warsaw
    - name: Disable IPv6 with sysctl
      ansible.posix.sysctl:
         name: "{{ item }}"
         value: "1"
         state: "present"
         reload: "yes"
      with_items:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6
######DOMENA
    - name: Instalacja pakietów
      apt:
        name: [ 'sssd-ad', 'sssd-tools', 'realmd', 'adcli', 'oddjob', 'oddjob-mkhomedir']
        state: latest
    - name: Kopiowanie pliku krb5.conf
      template:
          src: templates/krb5.conf
          dest: /etc/krb5.conf
    - name: Instalacja pakietów #2
      apt:
        name: [ 'krb5-user', 'sssd-krb5']
        state: latest        
    - name: Aktywacja mkhomedir
      ansible.builtin.shell: |
        sudo bash -c "cat > /usr/share/pam-configs/mkhomedir" <<EOF
            Name: activate mkhomedir
            Default: yes
            Priority: 900
            Session-Type: Additional
            Session:
            required                        pam_mkhomedir.so umask=0022 skel=/etc/skel
        EOF
     - name: Actually join the domain
      ansible.builtin.shell: |
          echo Mk090911| sudo realm join mksystem.com.pl -v -U utechniczny
          realm list
      register: results
    - name: See the results
      debug:
       msg: "{{ results }}"
    - name: Edit sshd config enable password authentication
      replace:
       path: /etc/ssh/sshd_config
       regexp: 'PasswordAuthentication no'
       replace: 'PasswordAuthentication yes'
    - name: Edit sshd config
      replace:
       path: /etc/ssh/sshd_config
       regexp: '#KerberosAuthentication no'
       replace: 'KerberosAuthentication no'
    - name: Edit sshd config
      replace:
       path: /etc/ssh/sshd_config
       regexp: '#KerberosOrLocalPasswd yes'
       replace: 'KerberosOrLocalPasswd yes'
    - name: Edit sshd config
      replace:
       path: /etc/ssh/sshd_config
       regexp: '#KerberosTicketCleanup yes'
       replace: 'KerberosTicketCleanup yes'
    - name: Edit sshd config
      replace:
       path: /etc/ssh/sshd_config
       regexp: '#KerberosGetAFSToken no'
       replace: 'KerberosGetAFSToken no'
    - name: Edit sshd config
      replace:
       path: /etc/ssh/sshd_config
       regexp: '#KerberosUseKuserok yes'
       replace: 'KerberosUseKuserok yes'
    - name: restart sshd
      service:
        name: sshd
        state: restarted
        enabled: True
    - name: Add sudoers
      ansible.builtin.shell: |
          echo "mkiljanski@mksystem.com.pl ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
