---
- hosts: gnome
  become: True
  remote_user: ansible
#  vars:
#    ansible_become_pass: Mk090911
  tasks:
    - name: Instalacja wymaganych pakietow do autoupdate
      apt:
        name:
        - unattended-upgrades
        cache_valid_time: 86400
  #####################
    - name: Przekopiowanie template
      copy:
        content: |
         APT::Periodic::Update-Package-Lists "1";
         APT::Periodic::Unattended-Upgrade "1";
        dest: /etc/apt/apt.conf.d/20auto-upgrades
    - name: Konfiguracja aktualizacji automatycznych
      template:
          src: templates/50unattended-upgrades
          dest: /etc/apt/apt.conf.d/50unattended-upgrades
    - name: Przekopiowanie zdefiniowanego pliku z banerem informacyjnym
      template:
          src: templates/greeter.dconf-defaults
          dest: /etc/gdm3/greeter.dconf-defaults
    - name: Ustawieenie wygaszacza
      ansible.builtin.shell: sudo -Hu mmk dbus-launch gsettings set org.gnome.desktop.session idle-delay 3600
- name: ufw enabled
      community.general.ufw:
        state: "enabled"
        policy: "deny"
        logging: "on"
    - name: ufw rules
      community.general.ufw:
        rule: "allow"
        port: "{{ item }}"
        proto: "tcp"
      with_items:
        - "22"
        - "80"
        - "443"
    - name: Set timezone to Europe/Warsaw
      community.general.timezone:
        name: Europe/Warsaw
    - name: Disable IPv6 with sysctl
      ansible.posix.sysctl:
         name: "{{ item }}"
         value: "1"
         state: "present"
         reload: "yes"
      with_items:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6
