---
- hosts: gnome
  become: True
  remote_user: ansible
#  vars:
#    ansible_become_pass: Mk090911
  tasks:
    - name: Instalacja wymaganych pakietow do autoupdate
      apt:
        name:
        - unattended-upgrades
        cache_valid_time: 86400
  #####################
    - name: Przekopiowanie template
      copy:
        content: |
         APT::Periodic::Update-Package-Lists "1";
         APT::Periodic::Unattended-Upgrade "1";
        dest: /etc/apt/apt.conf.d/20auto-upgrades
    - name: Konfiguracja aktualizacji automatycznych
      template:
          src: templates/50unattended-upgrades
          dest: /etc/apt/apt.conf.d/50unattended-upgrades
    - name: Przekopiowanie zdefiniowanego pliku z banerem informacyjnym
      template:
          src: templates/greeter.dconf-defaults
          dest: /etc/gdm3/greeter.dconf-defaults
    - name: Ustawieenie wygaszacza
      ansible.builtin.shell: sudo -Hu mmk dbus-launch gsettings set org.gnome.desktop.session idle-delay 3600
    - name: ufw enabled
      community.general.ufw:
        state: "enabled"
        policy: "deny"
        logging: "on"
    - name: ufw rules
      community.general.ufw:
        rule: "allow"
        port: "{{ item }}"
        proto: "tcp"
      with_items:
        - "22"
        - "80"
        - "443"
    - name: Set timezone to Europe/Warsaw
      community.general.timezone:
        name: Europe/Warsaw
    - name: Disable IPv6 with sysctl
      ansible.posix.sysctl:
         name: "{{ item }}"
         value: "1"
         state: "present"
         reload: "yes"
      with_items:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6
######DOMENA
    - name: Install dependencies
    apt:
      name: ['realmd','sssd','oddjob','oddjob-mkhomedir','adcli','krb5-workstation','samba-common-tools','sssd-ad']
      state: latest
    - name: Actually join the domain
    shell: |
      echo "Mk09091" | realm join mksystem.eu -v -U Mk090911
      realm permit -g LINADMIN@redwood.com
      realm permit -g SDESK@redwood.com
      realm list
    register: results
    - name: See the results
    debug:
      msg: "{{ results }}"

    - name: Edit sshd config enable password authentication
    replace:
      path: /etc/ssh/sshd_config
      regexp: 'PasswordAuthentication no'
      replace: 'PasswordAuthentication yes'
    - name: Edit sshd config
    replace:
      path: /etc/ssh/sshd_config
      regexp: '#KerberosAuthentication no'
      replace: 'KerberosAuthentication no'
    - name: Edit sshd config
    replace:
      path: /etc/ssh/sshd_config
      regexp: '#KerberosOrLocalPasswd yes'
      replace: 'KerberosOrLocalPasswd yes'
    - name: Edit sshd config
    replace:
      path: /etc/ssh/sshd_config
      regexp: '#KerberosTicketCleanup yes'
      replace: 'KerberosTicketCleanup yes'
    - name: Edit sshd config
    replace:
      path: /etc/ssh/sshd_config
      regexp: '#KerberosGetAFSToken no'
      replace: 'KerberosGetAFSToken no'
    - name: Edit sshd config
    replace:
      path: /etc/ssh/sshd_config
      regexp: '#KerberosUseKuserok yes'
      replace: 'KerberosUseKuserok yes'
    - name: restart sshd
    service:
      name: sshd
      state: restarted
    - name: Add sudoers
    shell: |
      echo "mkiljanski@mksystem.eu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
