---
- hosts: webservers 
  become: True
  remote_user: ansible
  vars:
    ansible_become_pass: Warszawa
  tasks:
- name: "Uninstall packages"
  apt:
    name: nginx
    state: absent
    autoremove: yes
