---
- hosts: webservers 
  become: True
  remote_user: ansible
  vars:
    ansible_become_pass: Warszawa
  tasks:
    - name: Remove nginx package
      apt:
        name: nginx
        state: absent
