---
- hosts: webservers 
  become: True
  remote_user: ansible
  vars:
    ansible_become_pass: Warszawa
  tasks:
    - name: Start nginx server
      service:
        name: nginx
        state: stopped
        enabled: False
    - name: Install packages
      apt:
        name: "nginx"
        state: "absent"
