---
- hosts: webservers 
  become: True
  remote_user: ansible
  vars:
    ansible_become_pass: Warszawa
  tasks:
    - name: Stop nginx
      service:
        name: nginx
        state: stopped
        enabled: False
    - name: Remove packages
      apt:
        name: nginx
        state: absent
        purge: yes
        autoremove: yes
