---
- hosts: webservers 
  become: True
  remote_user: ansible
  vars:
    ansible_become_pass: Warszawa
  tasks:
- name: Remove nginx package
  ansible.builtin.dnf:
    name: nginx
    state: absent
