---
- hosts: webservers 
  become: True
  remote_user: ansible
  vars:
    ansible_become_pass: Warszawa
  tasks:
    - name: ufw enabled
      community.general.ufw:
        state: "enabled"
        policy: "deny"
        logging: "on"
    - name: ufw rules
      community.general.ufw:
        rule: "allow"
        port: "{{ item }}"
        proto: "tcp"
      with_items:
        - "22"
        - "80"
        - "443"
    - name: Set timezone to Asia/Tokyo
      community.general.timezone:
        name: Europe/Warsaw
    - name: Disable IPv6 with sysctl
      ansible.posix.sysctl:
         name: "{{ item }}"
         value: "1"
         state: "present"
         reload: "yes"
       with_items:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6
