---
- hosts: webservers 
  become: True
  remote_user: ansible
  vars:
    ansible_become_pass: Warszawa
  tasks:
    - name: ufw enabled
      community.general.ufw:
        state: "enabled"
        policy: "deny"
        logging: "on"
    - name: ufw rules
      community.general.ufw:
        rule: "allow"
        port: "{{ item }}"
        proto: "tcp"
      with_items:
        - "22"
        - "80"
        - "443"
    - name: Set timezone to Europe/Warsaw
      community.general.timezone:
        name: Europe/Warsaw
    - name: Disable IPv6 with sysctl
      ansible.posix.sysctl:
         name: "{{ item }}"
         value: "1"
         state: "present"
         reload: "yes"
      with_items:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6
    - name: Install required packages for autoupdate
  apt:
    name:
      - unattended-upgrades
      - sendmail
    cache_valid_time: 86400

- name: Enable automatic update / upgrade
  copy:
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    dest: /etc/apt/apt.conf.d/20auto-upgrades

- name: Configure unattended upgrades
  template:
    src: templates/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
